# Generated by Django 5.0.3 on 2024-04-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='convenio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
